config/routes.rb
Rails.application.routes.draw do
  resources :student_courses
  resources :courses
  resources :students

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  #
  ## Association
  #
  has_many :student_courses
  has_many :students, through: :student_courses

  #
  ## Validation
  #
  validates :name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  #
  ## Association
  #
  has_many :student_courses
  has_many :courses, through: :student_courses

  #
  ## Validation
  #
  validates :name, :city, presence: true
  validates :perent_mobile, presence: true, numericality: true, length: { minimum: 10, maximum: 10 }
  validates :mobile, presence: true, numericality: true, length: { minimum: 10, maximum: 10 }
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_path(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_path(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_path, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find_by(id: params[:id])
      redirect_to courses_path if @course.blank?
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  before_action :set_student_course, only: %i[ show edit update destroy ]

  def index
    @student_courses = StudentCourse.all
  end

  def show
  end

  def new
    @student_course = StudentCourse.new
  end

  def edit
  end

  def create
    @student_course = StudentCourse.new(student_course_params)

    respond_to do |format|
      if @student_course.save
        format.html { redirect_to student_course_path(@student_course), notice: "Student course was successfully created." }
        format.json { render :show, status: :created, location: @student_course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student_course.update(student_course_params)
        format.html { redirect_to student_course_path(@student_course), notice: "Student course was successfully updated." }
        format.json { render :show, status: :ok, location: @student_course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student_course.destroy

    respond_to do |format|
      format.html { redirect_to student_courses_path, notice: "Student course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_course
      @student_course = StudentCourse.find_by(id: params[:id])
      redirect_to student_courses_path if @student_course.blank?
    end

    # Only allow a list of trusted parameters through.
    def student_course_params
      params.require(:student_course).permit(:student_id, :course_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  def index

    @record_filter = Student.ransack(params[:search])
    @students = @record_filter.result(distinct: true)

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "test", template: "/students/student_list.html.erb", formats: [:html], layout: "pdf"
      end
      format.xls do
        render xls: "test", template: "/students/student_list.html.erb", formats: [:html], layout: "pdf"
      end
    end
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_path(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_path(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_path, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find_by(id: params[:id])
      redirect_to students_path if @student.blank?
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :perent_mobile, :mobile, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def student_list
    Student.pluck(:name, :id)
  end

  def course_list
    Course.pluck(:name, :id)
  end
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary"%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Editing Course</h4>
  </div>
</div>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path, class: "btn btn-outline-primary" %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Courses</h4>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class: "btn btn-outline-primary" %> |
<%= link_to 'Dashbord', root_path, class: "btn btn-outline-primary" %>

app/views/courses/new.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">New Course</h4>
  </div>
</div>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path, class: "btn btn-outline-primary" %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course), class: "btn btn-outline-primary" %> |
<%= link_to 'Back', courses_path, class: "btn btn-outline-primary" %>

<div class="card mb-4 mt-4">
  <div class="card-body">
    <h4 class="text-center">Student Details</h4>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @course.students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class="card bg-dark p-4">
  <div class="card-body">
    <h3 class="m-2 card-title text-white">Welcome Dashbord</h3>

    <%= link_to "Students", students_path, class: "btn btn-outline-primary text-white m-2" %>
    <%= link_to "Courses", courses_path, class: "btn btn-outline-primary text-white m-2" %>
    <%= link_to "Student Courses", student_courses_path, class: "btn btn-outline-primary text-white m-2" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentData</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/student_courses/_form.html.erb
<%= form_with(model: student_course) do |form| %>
  <% if student_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_course.errors.count, "error") %> prohibited this student_course from being saved:</h2>

      <ul>
        <% student_course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= form.label :student_id %>
    <%= form.select :student_id, student_list,{ prompt: 'Select Student' }, class: "form-select" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :course_id %>
    <%= form.select :course_id, course_list, { prompt: 'Select Course' }, class: "form-select" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/student_courses/edit.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Editing Student Course</h4>
  </div>
</div>

<%= render 'form', student_course: @student_course %>

<%= link_to 'Back', student_courses_path, class: "btn btn-outline-primary" %>

app/views/student_courses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Student Courses</h4>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_courses.each do |student_course| %>
      <tr>
        <td><%= student_course.student.name %></td>
        <td><%= student_course.course.name %></td>
        <td><%= link_to 'Show', student_course %></td>
        <td><%= link_to 'Edit', edit_student_course_path(student_course) %></td>
        <td><%= link_to 'Destroy', student_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Course', new_student_course_path, class: "btn btn-outline-primary" %> |
<%= link_to 'Dashbord', root_path, class: "btn btn-outline-primary" %>

app/views/student_courses/new.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">New Student Course</h4>
  </div>
</div>

<%= render 'form', student_course: @student_course %>

<%= link_to 'Back', student_courses_path, class: "btn btn-outline-primary" %>

app/views/student_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student Name:</strong>
  <%= @student_course.student.name %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @student_course.course.name %>
</p>

<%= link_to 'Edit', edit_student_course_path(@student_course), class: "btn btn-outline-primary" %> |
<%= link_to 'Back', student_courses_path, class: "btn btn-outline-primary"%>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :perent_mobile %>
    <%= form.text_field :perent_mobile, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, class: "form-control" %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Editing Student</h4>
  </div>
</div>


<%= render 'form', student: @student %>
<%= link_to 'Back', students_path, class: "btn btn-outline-primary" %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Students List</h4>
  </div>
</div>


<div class="card mb-4">
  <div class="card-body">
      <h4 class="text-center mb-5">Searching Area</h4>
      <%= search_form_for @record_filter, url: :students do |f| %>
        <div class="row">
          <div class='col-sm-3'>
            <div class="form-group">
              <%#= f.label :name %>
              <%= f.search_field :name_cont, class: 'form-control', placeholder: "Name Search..." %>
            </div>
          </div>
          <div class='col-sm-3'>
            <div class="form-group">
              <%#= f.label :perent_mobile %>
              <%= f.search_field :perent_mobile_cont, class: 'form-control', placeholder: "Perent mobile number search..." %>
            </div>
          </div>
          <div class='col-sm-3'>
            <div class="form-group">
              <%= f.submit 'Search', class: 'btn btn-block btn-outline-primary' %>
            </div>
          </div>
          <div class='col-sm-3'>
            <%= link_to "Download xls", students_path(format: :xls), class:"btn btn-outline-primary" %>
            <%= link_to "Download pdf", students_path(format: :pdf), class:"btn btn-outline-primary" %>
          </div>
        </div>
      <% end %>
  </div>
</div>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Perent mobile</th>
      <th>Mobile</th>
      <th>City</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.perent_mobile %></td>
        <td><%= student.mobile %></td>
        <td><%= student.city %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: "btn btn-outline-primary" %> |
<%= link_to 'Dashbord', root_path, class: "btn btn-outline-primary" %>

app/views/students/new.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">New Student</h4>
  </div>
</div>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, class: "btn btn-outline-primary" %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Perent mobile:</strong>
  <%= @student.perent_mobile %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<p>
  <strong>City:</strong>
  <%= @student.city %>
</p>

<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-outline-primary"  %> |
<%= link_to 'Back', students_path, class: "btn btn-outline-primary"  %>


<div class="card mb-4 mt-4">
  <div class="card-body">
    <h4 class="text-center">Courses Details</h4>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @student.courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/student_list.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h4 class="text-center">Student List</h4>
  </div>
</div>

<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Perent mobile</th>
      <th>Mobile</th>
      <th>City</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.perent_mobile %></td>
        <td><%= student.mobile %></td>
        <td><%= student.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>